---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rhbk-db
spec:
  serviceName: rhbk-db-service
  selector:
    matchLabels:
      app: rhbk-db
  replicas: 1
  template:
    metadata:
      labels:
        app: rhbk-db
    spec:
      containers:
        - name: rhbk-db
          image: registry.redhat.io/rhscl/postgresql-10-rhel7
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: rhbk-db-secret
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rhbk-db-secret
                  key: password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rhbk-db-secret
                  key: db_name
            - name: PGDATA
              value: /data/pgdata
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rhbk-db
spec:
  selector:
    app: rhbk-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
