---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/3scale-qe/go-httpbin
    newName: quay.io/rh_integration/go-httpbin
    newTag: smadis
  - name: quay.io/rh_integration/requestbin
    newName: quay.io/rh_integration/requestbin
    newTag: latest
  - name: registry.access.redhat.com/rhscl/redis-32-rhel7
    newName: registry.access.redhat.com/rhscl/redis-32-rhel7
    newTag: "3.2"
  - name: ghcr.io/3scale-qe/tinyproxy
    newName: quay.io/rh_integration/tinyproxy
    newTag: eloy
  - name: quay.io/jaegertracing/all-in-one
    newName: quay.io/rh_integration/jaeger-aio
    newTag: latest

resources:
  - ../../base/go-httpbin/
  - ../../base/request-bin/
  - ../../base/tiny-proxy/
  - ../../base/jaeger/
