---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/echo-api/
  - ../../base/fuse-proxy/
  - ../../base/go-httpbin/
  - ../../base/jaeger/
  - ../../base/mockserver/
