---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: minio

resources:
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service-api.yaml
  - service-console.yaml
  - route.yaml
  - route-console.yaml
