---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/httpbin/
  - ../../base/go-httpbin/
  - ../../base/request-bin/
  - ../../base/echo-api/
  - ../../base/fuse-proxy/
  - ../../base/tiny-proxy/
  - ../../base/mockserver/

