---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tinyproxy-config
data:
  tinyproxy.conf: |-
    User tinyproxy
    Group tinyproxy
    Port 8888
    ConnectPort 4443
    ConnectPort 443
    Timeout 600
    DefaultErrorFile "/usr/share/tinyproxy/default.html"
    StatFile "/usr/share/tinyproxy/stats.html"
    LogLevel info
    MaxClients 100
    MinSpareServers 5
    MaxSpareServers 20
    StartServers 10
    MaxRequestsPerChild 0
    ViaProxyName "tinyproxy"
    DisableViaHeader No
    XTinyproxy Yes
