apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
    folders: grafana
spec:
  config:
    auth.anonymous:
        enabled: 'true'
        org_role: Admin
    auth.basic:
        enabled: 'true'
    log:
      mode: console
    security:
      admin_password: admin
      admin_user: admin

