---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: echo-api
  app.kubernetes.io/component: echo-api
  app.kubernetes.io/instance: echo-api

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
