---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: httpbin
  app.kubernetes.io/component: httpbin
  app.kubernetes.io/instance: httpbin

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
