---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: no-ssl-sso
  name: no-ssl-sso
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: keycloak
    component: keycloak
  type: ClusterIP
