---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: jaeger

resources:
  - deployment.yaml
  - service-query.yaml
  - service-collector.yaml
  - service-agent.yaml
  - service-zipkin.yaml
  - route-query.yaml
